### ISSUE TITLE
Networkx version build error 

### ISSUE THREAD

**Issue by mozark24** [priba/aproximated_ged#1]
I get an error related to networkx when running main.py.  I have networkx installed (v2.1) and have used it in other projects.  What version of networkx is your build for?

Trace:
~/Desktop/CSCE899/aproximated_ged-master$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 38, in <module>
    distAED, _ = aed.ged(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 89, in ged
    cost_matrix = self.cost_matrix(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 63, in cost_matrix
    np.fill_diagonal(cost_matrix[len(g1):, 0:len(g2)], self.node_insertion(g1)+self.edge_insertion(g1.edge.values()))
AttributeError: 'Graph' object has no attribute 'edge'

**Comment by mozark24** [comment]
I reverted my NetworkX build to v1.9 and was able to get past this error.

**Comment by priba** [comment]
This problem was solved. I close the issue
