### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by mozark24** [priba/aproximated_ged#2]
Compilation failure in both AED and HED when attempting the following line:
v1 = [list(chain.from_iterable(l.values())) for l in values1]

My Python-fu is not strong enough to reason through this line get past this issue.  Running Python2.7.

./main.py
Traceback (most recent call last):
  File "./main.py", line 38, in <module>
    distAED, _ = aed.ged(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 89, in ged
    cost_matrix = self.cost_matrix(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 70, in cost_matrix
    node_dist = self.node_substitution(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/VanillaAED.py", line 52, in node_substitution
    v1 = [list(chain.from_iterable(l.values())) for l in values1]
TypeError: 'int' object is not iterable

**Comment by priba** [comment]
Hi @mozark24 
I've seen in #1  that you have installed networkx v1.9. When I was doing this code I was using v1.11. Would you mind to try with this other version?
Thank you

**Comment by mozark24** [comment]
Hello @priba, thank you for your prompt response.

I swapped over to v1.11 of networkx and now I believe i have a scipy issue in _hungarian.py.  What version of scipy were you using?

Here is my trace.  Would you like me to create a separate issue?
./main.py 
Traceback (most recent call last):
  File "./main.py", line 38, in <module>
    distAED, _ = aed.ged(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 89, in ged
    cost_matrix = self.cost_matrix(g1, g2)
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 76, in cost_matrix
    node_dist[i1, i2] += self.edge_ed(g1[k1], g2[k2])
  File "/home/chris/Desktop/CSCE899/aproximated_ged-master/AproximatedEditDistance.py", line 51, in edge_ed
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/_hungarian.py", line 93, in linear_sum_assignment
    raise ValueError("matrix contains invalid numeric entries")
ValueError: matrix contains invalid numeric entries

**Comment by priba** [comment]
Hi,

I am using scipy v0.18.1 and numpy v1.13.1, hope this helps

**Comment by mozark24** [comment]
That did the trick :)
Recommend adding this info to your requirements.txt file.

Thank you!

**Comment by priba** [comment]
Done.

Thank you!
